version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ml_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
